name: wassalni
description: A new Flutter project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  fl_country_code_picker: ^0.1.5
  pinput: ^2.3.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.1  # Correction de la dépendance cloud_firestore
  image_picker: ^0.8.5+3  # Correction de la dépendance image_picker
  firebase_storage: ^11.5.1 
  path: ^1.8.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    
