// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdo8ZW8c5F9xSoK8LPDofI3aoSPZhz0A',
    appId: '1:680054496945:web:a8c166cf0776f727400c90',
    messagingSenderId: '680054496945',
    projectId: 'yalla-taxi-336b2',
    authDomain: 'yalla-taxi-336b2.firebaseapp.com',
    databaseURL: 'https://yalla-taxi-336b2-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-taxi-336b2.appspot.com',
    measurementId: 'G-Z1FE24M4TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0taHo7aOdJ3YAk8ltakUuvdPK9-whalI',
    appId: '1:680054496945:android:7b5b8c2a2ccc9d23400c90',
    messagingSenderId: '680054496945',
    projectId: 'yalla-taxi-336b2',
    databaseURL: 'https://yalla-taxi-336b2-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-taxi-336b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5q_0tdb5-T8Tt1dkcF4V7_zZXk6u_ts',
    appId: '1:680054496945:ios:3f6ee089ba4d68f2400c90',
    messagingSenderId: '680054496945',
    projectId: 'yalla-taxi-336b2',
    databaseURL: 'https://yalla-taxi-336b2-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-taxi-336b2.appspot.com',
    iosBundleId: 'com.example.wassalni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5q_0tdb5-T8Tt1dkcF4V7_zZXk6u_ts',
    appId: '1:680054496945:ios:09f67469470b508b400c90',
    messagingSenderId: '680054496945',
    projectId: 'yalla-taxi-336b2',
    databaseURL: 'https://yalla-taxi-336b2-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-taxi-336b2.appspot.com',
    iosBundleId: 'com.example.wassalni.RunnerTests',
  );
}
